# Generated by Django 3.2 on 2021-04-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1app', '0002_place1'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='new',
            field=models.CharField(default='demo', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='pen',
            field=models.TextField(default='demo'),
            preserve_default=False,
        ),
    ]
