# Generated by Django 3.2 on 2021-04-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo1app', '0003_auto_20210423_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='new',
        ),
        migrations.RemoveField(
            model_name='place',
            name='pen',
        ),
    ]
