# Generated by Django 3.2 on 2021-04-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1app', '0004_auto_20210423_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='non',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
